// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottomPane': string;
  'splitScreen': string;
  'topPane': string;
}
export const cssExports: CssExports;
export default cssExports;
