// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'react-tabs': string;
  'react-tabs__tab': string;
  'react-tabs__tab--disabled': string;
  'react-tabs__tab--selected': string;
  'react-tabs__tab-list': string;
  'react-tabs__tab-panel': string;
  'react-tabs__tab-panel--selected': string;
}
export const cssExports: CssExports;
export default cssExports;
